-- Auto-generated from schema-map-postgres.yaml (map@sha1:6D9B52237D942B2B3855FD0F5500331B935A7C62)
-- engine: postgres
-- table:  session_audit

CREATE TABLE IF NOT EXISTS session_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_token_hash BYTEA NULL,
  session_token_key_version VARCHAR(64) NULL,
  csrf_token_hash BYTEA NULL,
  csrf_key_version VARCHAR(64) NULL,
  session_id VARCHAR(128) NULL,
  event VARCHAR(64) NOT NULL,
  user_id BIGINT NULL,
  ip_hash BYTEA NULL,
  ip_hash_key_version VARCHAR(64) NULL,
  user_agent VARCHAR(1024) NULL,
  meta_json JSONB NULL,
  outcome VARCHAR(32) NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);
